### ISSUE TITLE
Wrong documentation link

### ISSUE THREAD

**Issue by kkiermasz** [swift-server/swift-openapi-hummingbird#1]
The documentation link in [README](https://github.com/swift-server/swift-openapi-hummingbird/blob/main/README.md) redirects to a non-existent page. I don't see a `docs` directory or anything like that, so I can't open the PR :/ 
LMK if I can help in any way :)

**Comment by adam-fowler** [comment]
Documentation is currently unavailable. It will come online soon.

**Comment by adam-fowler** [comment]
This should be resolved now
